### ISSUE TITLE
Example link returns 404 ?

### ISSUE THREAD

**Issue by 2dvisio** [ledancs/hFigures#1]
Hi, the link to the sample page http://interact.oulu.fi/hFigures/nutrition.html is not working and for some reason the server returns a 404.

Cheers.

**Comment by ledancs** [comment]
Yep this was a student's Master thesis, it seems they took the website down. 
I made a copy of the dataset so I would be able to upload a working version on another site.
Thanks for reporting it! I start to host this on our home University's website from now on.
I will report back to you as soon as I get news.
By the way, you  can easily download the repository and open the simple.html or complex.html files with any browser, then you will see a live demo on your own box :)

**Comment by ledancs** [comment]
The live demo is now up and running :)
We spoke with the guys from Oulu University and the live demo will be online for the time being.
